Require go1.11+
decred/base58 pull request #9
Opened 2018-10-24 20:57 UTC by dajohi

2019-02-04 23:30 UTC, davecgh requested changes
While I personally very much prefer just using Travis containers over Docker for the tests, is there any reason this repo is being made inconsistent with dcrd/dcrwallet in this regard?

2019-02-04 23:30 UTC, davecgh commented on base58check_test.go
> +		case err != nil:
Please don't change this.  Making error checks inconsistent with virtually every other case is not at all desirable.

2019-02-18 15:01 UTC, dajohi commented on base58check_test.go
> +		case err != nil:
reverted

2019-03-18 23:07 UTC, davecgh approved these changes

2019-03-18 23:07 UTC, merged